mkoctfile --mex -Icommon  -o toolbox/aBPtrain.mex source/lda/bp/bp/aBPtrain.cpp              
mkoctfile --mex -Icommon  -o toolbox/aBPpredict.mex source/lda/bp/bp/aBPpredict.cpp            
mkoctfile --mex -Icommon  -o toolbox/sBPtrain.mex source/lda/bp/bp/sBPtrain.cpp              
mkoctfile --mex -Icommon  -o toolbox/sBPpredict.mex source/lda/bp/bp/sBPpredict.cpp            
mkoctfile --mex -Icommon  -o toolbox/asiBPtrain.mex source/lda/bp/simplified/asiBPtrain.cpp    
mkoctfile --mex -Icommon  -o toolbox/asiBPpredict.mex source/lda/bp/simplified/asiBPpredict.cpp  
mkoctfile --mex -Icommon  -o toolbox/ssiBPtrain.mex source/lda/bp/simplified/ssiBPtrain.cpp    
mkoctfile --mex -Icommon  -o toolbox/ssiBPpredict.mex source/lda/bp/simplified/ssiBPpredict.cpp  
mkoctfile --mex -Icommon  -o toolbox/aCVB0train.mex source/lda/bp/cvb0/aCVB0train.cpp          
mkoctfile --mex -Icommon  -o toolbox/aCVB0predict.mex source/lda/bp/cvb0/aCVB0predict.cpp        
mkoctfile --mex -Icommon  -o toolbox/sCVB0train.mex source/lda/bp/cvb0/sCVB0train.cpp          
mkoctfile --mex -Icommon  -o toolbox/sCVB0predict.mex source/lda/bp/cvb0/sCVB0predict.cpp        
mkoctfile --mex -Icommon  -o toolbox/VBtrain.mex source/lda/vb/VBtrain.cpp                  
mkoctfile --mex -Icommon  -o toolbox/VBpredict.mex source/lda/vb/VBpredict.cpp                
mkoctfile --mex -Icommon  -o toolbox/GStrain.mex source/lda/gs/GStrain.cpp                  
mkoctfile --mex -Icommon  -o toolbox/GSpredict.mex source/lda/gs/GSpredict.cpp                
mkoctfile --mex -Icommon  -o toolbox/ATMBPtrain.mex source/atm/bp/ATMBPtrain.cpp               
mkoctfile --mex -Icommon  -o toolbox/ATMBPpredict.mex source/atm/bp/ATMBPpredict.cpp             
mkoctfile --mex -Icommon  -o toolbox/ATMGStrain.mex source/atm/gs/ATMGStrain.cpp               
mkoctfile --mex -Icommon  -o toolbox/ATMGSpredict.mex source/atm/gs/ATMGSpredict.cpp             
mkoctfile --mex -Icommon  -o toolbox/RTMBPtrain.mex source/rtm/bp/RTMBPtrain.cpp               
mkoctfile --mex -Icommon  -o toolbox/RTMBPpredict.mex source/rtm/bp/RTMBPpredict.cpp             
mkoctfile --mex -Icommon  -o toolbox/LaLDABPtrain.mex source/lalda/bp/LaLDABPtrain.cpp           
mkoctfile --mex -Icommon  -o toolbox/FGStrain.mex source/lda/gs/FGStrain.cpp                 
mkoctfile --mex -Icommon  -o toolbox/FGSpredict.mex source/lda/gs/FGSpredict.cpp               
mkoctfile --mex -Icommon  -o toolbox/FBPtrain_doc.mex source/lda/bp/fast/FBPtrain_doc.cpp        
mkoctfile --mex -Icommon  -o toolbox/FBPpredict_doc.mex source/lda/bp/fast/FBPpredict_doc.cpp      
mkoctfile --mex -Icommon  -o toolbox/FBPtrain_voc.mex source/lda/bp/fast/FBPtrain_voc.cpp        
mkoctfile --mex -Icommon  -o toolbox/FBPpredict_voc.mex source/lda/bp/fast/FBPpredict_voc.cpp      
mkoctfile --mex -Icommon  -o toolbox/RBPtrain_doc.mex source/lda/bp/residual/RBPtrain_doc.cpp    
mkoctfile --mex -Icommon  -o toolbox/RBPpredict_doc.mex source/lda/bp/residual/RBPpredict_doc.cpp  
mkoctfile --mex -Icommon  -o toolbox/RBPtrain_voc.mex source/lda/bp/residual/RBPtrain_voc.cpp    
mkoctfile --mex -Icommon  -o toolbox/RBPpredict_voc.mex source/lda/bp/residual/RBPpredict_voc.cpp            
mkoctfile --mex -Icommon  -o toolbox/ABPtrain_doc.mex source/lda/bp/active/ABPtrain_doc.cpp      
mkoctfile --mex -Icommon  -o toolbox/ABPpredict_doc.mex source/lda/bp/active/ABPpredict_doc.cpp    
mkoctfile --mex -Icommon  -o toolbox/ABPtrain_voc.mex source/lda/bp/active/ABPtrain_voc.cpp      
mkoctfile --mex -Icommon  -o toolbox/ABPpredict_voc.mex source/lda/bp/active/ABPpredict_voc.cpp    
mkoctfile --mex -Icommon  -o toolbox/aTBPtrain.mex source/lda/bp/tiny/aTBPtrain.cpp            
mkoctfile --mex -Icommon  -o toolbox/aTBPpredict.mex source/lda/bp/tiny/aTBPpredict.cpp
mkoctfile --mex -Icommon  -o toolbox/sTBPtrain.mex source/lda/bp/tiny/sTBPtrain.cpp            
mkoctfile --mex -Icommon  -o toolbox/sTBPpredict.mex source/lda/bp/tiny/sTBPpredict.cpp
mkoctfile --mex -Icommon  -o toolbox/aTBPtrain_file.mex source/lda/bp/tiny/aTBPtrain_file.cpp            
mkoctfile --mex -Icommon  -o toolbox/aTBPpredict_file.mex source/lda/bp/tiny/aTBPpredict_file.cpp
mkoctfile --mex -Icommon  -o toolbox/sTBPtrain_file.mex source/lda/bp/tiny/sTBPtrain_file.cpp            
mkoctfile --mex -Icommon  -o toolbox/sTBPpredict_file.mex source/lda/bp/tiny/sTBPpredict_file.cpp
mkoctfile --mex -Icommon  -o toolbox/MAT2WD.mex datasets/utilities/MAT2WD.cpp            
mkoctfile --mex -Icommon  -o toolbox/UCI2WD.mex datasets/utilities/UCI2WD.cpp
