mex  -Icommon -outdir toolbox/  source/lda/bp/bp/aBPtrain.cpp              
mex  -Icommon -outdir toolbox/  source/lda/bp/bp/aBPpredict.cpp            
mex  -Icommon -outdir toolbox/  source/lda/bp/bp/sBPtrain.cpp              
mex  -Icommon -outdir toolbox/  source/lda/bp/bp/sBPpredict.cpp            
mex  -Icommon -outdir toolbox/  source/lda/bp/simplified/asiBPtrain.cpp    
mex  -Icommon -outdir toolbox/  source/lda/bp/simplified/asiBPpredict.cpp  
mex  -Icommon -outdir toolbox/  source/lda/bp/simplified/ssiBPtrain.cpp    
mex  -Icommon -outdir toolbox/  source/lda/bp/simplified/ssiBPpredict.cpp  
mex  -Icommon -outdir toolbox/  source/lda/bp/cvb0/aCVB0train.cpp          
mex  -Icommon -outdir toolbox/  source/lda/bp/cvb0/aCVB0predict.cpp        
mex  -Icommon -outdir toolbox/  source/lda/bp/cvb0/sCVB0train.cpp          
mex  -Icommon -outdir toolbox/  source/lda/bp/cvb0/sCVB0predict.cpp        
mex  -Icommon -outdir toolbox/  source/lda/vb/VBtrain.cpp                  
mex  -Icommon -outdir toolbox/  source/lda/vb/VBpredict.cpp                
mex  -Icommon -outdir toolbox/  source/lda/gs/GStrain.cpp                  
mex  -Icommon -outdir toolbox/  source/lda/gs/GSpredict.cpp                
mex  -Icommon -outdir toolbox/  source/atm/bp/ATMBPtrain.cpp               
mex  -Icommon -outdir toolbox/  source/atm/bp/ATMBPpredict.cpp             
mex  -Icommon -outdir toolbox/  source/atm/gs/ATMGStrain.cpp               
mex  -Icommon -outdir toolbox/  source/atm/gs/ATMGSpredict.cpp             
mex  -Icommon -outdir toolbox/  source/rtm/bp/RTMBPtrain.cpp               
mex  -Icommon -outdir toolbox/  source/rtm/bp/RTMBPpredict.cpp             
mex  -Icommon -outdir toolbox/  source/lalda/bp/LaLDABPtrain.cpp           
mex  -Icommon -outdir toolbox/  source/lda/gs/FGStrain.cpp                 
mex  -Icommon -outdir toolbox/  source/lda/gs/FGSpredict.cpp               
mex  -Icommon -outdir toolbox/  source/lda/bp/fast/FBPtrain_doc.cpp        
mex  -Icommon -outdir toolbox/  source/lda/bp/fast/FBPpredict_doc.cpp      
mex  -Icommon -outdir toolbox/  source/lda/bp/fast/FBPtrain_voc.cpp        
mex  -Icommon -outdir toolbox/  source/lda/bp/fast/FBPpredict_voc.cpp      
mex  -Icommon -outdir toolbox/  source/lda/bp/residual/RBPtrain_doc.cpp    
mex  -Icommon -outdir toolbox/  source/lda/bp/residual/RBPpredict_doc.cpp  
mex  -Icommon -outdir toolbox/  source/lda/bp/residual/RBPtrain_voc.cpp    
mex  -Icommon -outdir toolbox/  source/lda/bp/residual/RBPpredict_voc.cpp            
mex  -Icommon -outdir toolbox/  source/lda/bp/active/ABPtrain_doc.cpp      
mex  -Icommon -outdir toolbox/  source/lda/bp/active/ABPpredict_doc.cpp    
mex  -Icommon -outdir toolbox/  source/lda/bp/active/ABPtrain_voc.cpp      
mex  -Icommon -outdir toolbox/  source/lda/bp/active/ABPpredict_voc.cpp    
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/aTBPtrain.cpp            
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/aTBPpredict.cpp
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/sTBPtrain.cpp            
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/sTBPpredict.cpp
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/aTBPtrain_file.cpp            
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/aTBPpredict_file.cpp
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/sTBPtrain_file.cpp            
mex  -Icommon -outdir toolbox/  source/lda/bp/tiny/sTBPpredict_file.cpp
mex  -Icommon -outdir toolbox/  datasets/utilities/MAT2WD.cpp
mex  -Icommon -outdir toolbox/  datasets/utilities/UCI2WD.cpp
